name: 'Trigger-Binder-build'
on:
  push:
    branches:
      - main

jobs:
  trigger-binder-build:
    runs-on: [ubuntu-latest]
    steps:
      - uses: dgerosa/trigger-mybinder-build@e60aa980afcc7b8c535587c2e921e1bd04aadd4d
        with:
          target-repo: dgerosa/astrostatistics_bicocca_2022
          service-name: gh
          target-state: HEAD
          use-default-build-servers: true
          debug: true
