name: Binder
on:
  push:
    branches:
      - main

jobs:
  Create-MyBinderOrg-Cache:
    runs-on: ubuntu-latest
    steps:
    - name: cache binder build on mybinder.org
      uses: machine-learning-apps/repo2docker-action@master
      with:
        NO_PUSH: true
        MYBINDERORG_TAG: main
